### ISSUE TITLE
Implement travel

### ISSUE THREAD

**Issue by raboley** [raboley/FantasyAi#1]
At the end of this, the bot should be able to run from one one to another.

**Comment by 0pdd** [comment]
@raboley 2 puzzles [#2](https://github.com/raboley/FantasyAi/issues/2), [#3](https://github.com/raboley/FantasyAi/issues/3) are still not solved.

**Comment by 0pdd** [comment]
@raboley 2 puzzles [#2](https://github.com/raboley/FantasyAi/issues/2), [#5](https://github.com/raboley/FantasyAi/issues/5) are still not solved; solved: [#3](https://github.com/raboley/FantasyAi/issues/3).

**Comment by 0pdd** [comment]
@raboley the puzzle [#2](https://github.com/raboley/FantasyAi/issues/2) is still not solved; solved: [#3](https://github.com/raboley/FantasyAi/issues/3), [#5](https://github.com/raboley/FantasyAi/issues/5).

**Comment by 0pdd** [comment]
@raboley the puzzle [#7](https://github.com/raboley/FantasyAi/issues/7) is still not solved; solved: [#2](https://github.com/raboley/FantasyAi/issues/2), [#3](https://github.com/raboley/FantasyAi/issues/3), [#5](https://github.com/raboley/FantasyAi/issues/5).

**Comment by 0pdd** [comment]
@raboley all 4 puzzles are solved here: [#2](https://github.com/raboley/FantasyAi/issues/2), [#3](https://github.com/raboley/FantasyAi/issues/3), [#5](https://github.com/raboley/FantasyAi/issues/5), [#7](https://github.com/raboley/FantasyAi/issues/7).

**Comment by raboley** [comment]
Can now travel between two places.
