### ISSUE TITLE
Make Talk consistently perform the talking actions expected

### ISSUE THREAD

**Issue by raboley** [raboley/FantasyAi#26]
Right now there is high liklihood of talk not working correctly (getting stuck in convo, or accidentally choosing options)

* Make starting conversations more consistent
* Make it so if we skip an expected dialog option it can pick up at the next place
* Potentially rework the logic to determine if in a dialog, or conversation (maybe something to do with setting targets?)

**Comment by 0pdd** [comment]
@raboley the puzzle [#29](https://github.com/raboley/FantasyAi/issues/29) is still not solved.

**Comment by 0pdd** [comment]
@raboley the only puzzle [#29](https://github.com/raboley/FantasyAi/issues/29) is solved here.

**Comment by raboley** [comment]
talking is much more consistent now.
