### ISSUE TITLE
Add the ability to go get signet

### ISSUE THREAD

**Issue by raboley** [raboley/FantasyAi#9]

**Comment by 0pdd** [comment]
@raboley the puzzle [#10](https://github.com/raboley/FantasyAi/issues/10) is still not solved.

**Comment by 0pdd** [comment]
@raboley the puzzle [#12](https://github.com/raboley/FantasyAi/issues/12) is still not solved; solved: [#10](https://github.com/raboley/FantasyAi/issues/10).

**Comment by 0pdd** [comment]
@raboley all 2 puzzles are solved here: [#10](https://github.com/raboley/FantasyAi/issues/10), [#12](https://github.com/raboley/FantasyAi/issues/12).

**Comment by raboley** [comment]
Closed! Bot will now go get Signet when it needs it!

**Comment by raboley** [comment]
#15
